id: PC4CFCFEB
initial_creation_type: ocr
source_metadata:
  volumes:
    1750ce05ade04bfc986e4e4c36047301:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཁྱད་པར་དུ་འཕགས་པའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
